### ISSUE TITLE
Team Slack Channel To Keep Everyone Updated

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Grow-With-Google-Team-Project#43]
Please Join this channel. -- > https://growwithgoogleteam.slack.com

**Comment by Madonahs** [comment]
cc @dri94 @radoalbert110 @Julianp1 @SrChip15 @MaherSoua  @CleverChuk  @HemantNimje  @Jantzilla

**Comment by MaherSoua** [comment]
I cannot access this workspace :(

**Comment by Madonahs** [comment]
I think @Emmanuel created maybe he should invite people ... Lol.

**Comment by MaherSoua** [comment]
ok :)

**Comment by JulianPhillips** [comment]
Can Emmanuel also invite me?

**Comment by Madonahs** [comment]
@JulianPhillips please send me your email i will right away :)

**Comment by JulianPhillips** [comment]
julian.park1988@gmail.com @Madonahs

**Comment by Madonahs** [comment]
@JulianPhillips  thanks :)

**Comment by Madonahs** [comment]
@JulianPhillips Sent 👍
